In [3]:
from tensorflow.keras.preprocessing.text import one_hot

In [7]:
sent = [
    'The glass of milk',
    'The glass of juice',
    'The cup of tea',
    'I am a good boy',
    'I am a good developer',
    'Understand the meaning of words',
    'Your videos are good'
]

In [8]:
vocab_size = 10000
onehot_repr = [one_hot(words, vocab_size) for words in sent]

In [9]:
onehot_repr

[[1842, 1256, 3836, 4275],
 [1842, 1256, 3836, 4003],
 [1842, 3267, 3836, 6032],
 [8127, 6519, 9542, 5550, 5788],
 [8127, 6519, 9542, 5550, 5219],
 [1023, 1842, 9917, 3836, 2332],
 [7910, 6329, 5190, 5550]]

In [11]:
#word Embedding Represntation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
#from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [12]:
import numpy as np


In [13]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 1842 1256 3836 4275]
 [   0    0    0    0 1842 1256 3836 4003]
 [   0    0    0    0 1842 3267 3836 6032]
 [   0    0    0 8127 6519 9542 5550 5788]
 [   0    0    0 8127 6519 9542 5550 5219]
 [   0    0    0 1023 1842 9917 3836 2332]
 [   0    0    0    0 7910 6329 5190 5550]]


In [14]:
#feature representation
dim=10


In [21]:
model=Sequential()
model.add(Embedding(vocab_size,dim,input_length=sent_length))
model.compile('adam','mse')

f:\anacoda3\Lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [22]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [23]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 347ms/step


array([[[ 0.02579749,  0.04449462,  0.03958264,  0.01334149,
          0.04826231,  0.03398171, -0.03515784, -0.04659451,
          0.01462858,  0.00253595],
        [ 0.02579749,  0.04449462,  0.03958264,  0.01334149,
          0.04826231,  0.03398171, -0.03515784, -0.04659451,
          0.01462858,  0.00253595],
        [ 0.02579749,  0.04449462,  0.03958264,  0.01334149,
          0.04826231,  0.03398171, -0.03515784, -0.04659451,
          0.01462858,  0.00253595],
        [ 0.02579749,  0.04449462,  0.03958264,  0.01334149,
          0.04826231,  0.03398171, -0.03515784, -0.04659451,
          0.01462858,  0.00253595],
        [ 0.01253517,  0.00088073,  0.0488991 , -0.01707474,
         -0.04961587,  0.00866691, -0.02631531, -0.03537184,
          0.04885756, -0.03902136],
        [-0.00683315, -0.03168994, -0.04898937,  0.04820905,
         -0.02293321,  0.02982837,  0.00510364, -0.03512094,
          0.00285999, -0.00318915],
        [-0.02768337, -0.03488191, -0.02104406,  0.0